{{- if and (.Values.virtualService.http.enabled) (.Values.virtualService.http.requestAuthentication.enabled) }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ printf "%s-http" ( include "helmchart.fullname" . ) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helmchart.selectorLabels" . | nindent 6 }}
  {{- with .Values.virtualService.http.requestAuthentication.jwtRules }}
  jwtRules:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}