{{- with .Values.pod.disruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  {{- toYaml . | trim | nindent 2 -}}
  selector:
    matchLabels:
      {{- include "helmchart.selectorLabels" . | nindent 6 }}
{{- end }}