apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helmchart.fullname" . | printf "%s-namespace-reader" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helmchart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ include "helmchart.fullname" . | printf "%s-namespace-reader" }}
subjects:
- kind: ServiceAccount
  name: {{ include "helmchart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""