apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
